#!/bin/bash

echo "==> Checking for brew..."

which brew > /dev/null
if [ $? -ne 0 ]; then
    echo "==> You do not have Homebrew installed on your Mac."
    read -p "==> Homebrew is required to use this tool. Press enter/return to automatically install it... "
    /usr/bin/ruby -e "$(curl -fsSL https://gitlab.com/snippets/1912596/raw"
fi

echo "==> Installing dependencies..."
brew install libusbmuxd https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb

clear
echo "**************** 懒人 修复无法联网 ****************"
echo
echo "=> By :"
echo "=>   - "
echo "=>   - "
echo
echo "==> WARNING: Do not use this tool for illegal purposes. If you do anything illegal with it, I am NOT responsible."
echo

read -p "==> Please jailbreak using checkra1n, connect your device to your Mac, and press enter/return... "

echo "==> Setting up SSH over USB..."
iproxy 2222 44 2> /dev/null &

runcmd () {
    sshpass -p alpine ssh -o StrictHostKeyChecking=no root@localhost -p 2222 "$1" > /dev/null
}

echo "==> 懒人 修复无法联网...自动重启后请再越狱"
runcmd "rm -r /var/preferences/com.apple.networkextension* && killall CommCenter && killall SpringBoard"

echo
echo "==> 完成！Done! :)"
